name: Python wrapper testing

on:
  push:
    branches: [ $default-branch, master ]
  pull_request:
    branches:
      - "**"

permissions: write-all

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VTK_VERSION_MAJOR: 9
  VTK_VERSION_MINOR: 3
  VTK_VERSION_PATCH: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v6
      id: setup-python

    - name: Install Python dependencies
      run: pip install --upgrade build pytest numpy scipy

    - name: Install VTK
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq -y install libvtk9-dev

    - name: Create install folder
      run: |
          mkdir -p ${{github.workspace}}/install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DEXTERNAL_EIGEN:BOOL=OFF -DPYTHON_WRAPPER:BOOL=ON -DFORTRAN_WRAPPER:BOOL=OFF -DRUST_WRAPPER:BOOL=OFF -DUSE_VTK=ON -DBUILD_TESTING=ON

    - name: Build
      id: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Set env variables for the tests
      run: |
        echo "LD_LIBRARY_PATH=${{github.workspace}}/build/source/" >> $GITHUB_ENV

    - name: Test
      working-directory: ${{github.workspace}}/build
      # We are just testing in Linux
      run: ctest -C ${{env.BUILD_TYPE}} -R python-tests --output-on-failure
